
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.fruitsdelight]
				pear = true
				hawberry = true
				lychee = true
				mango = true
				persimmon = true
				peach = true
				orange = true
				apple = true
				mangosteen = true
				bayberry = true
				kiwi = true
				fig = true
				durian = true

			[general.types.leaves_type.chipped]
				apple_acacia = true
				cherry_acacia = true
				dead_acacia = true
				frosted_acacia = true
				golden_acacia = true
				golden_apple_acacia = true
				golden_cherry_acacia = true
				magenta_flower_acacia = true
				orange_acacia = true
				red_acacia = true
				white_flower_acacia = true
				apple_birch = true
				cherry_birch = true
				dead_birch = true
				frosted_birch = true
				golden_birch = true
				golden_apple_birch = true
				golden_cherry_birch = true
				magenta_flower_birch = true
				orange_birch = true
				red_birch = true
				white_flower_birch = true
				apple_dark_oak = true
				cherry_dark_oak = true
				dead_dark_oak = true
				frosted_dark_oak = true
				golden_dark_oak = true
				golden_apple_dark_oak = true
				golden_cherry_dark_oak = true
				magenta_flower_dark_oak = true
				orange_dark_oak = true
				red_dark_oak = true
				white_flower_dark_oak = true
				apple_jungle = true
				cherry_jungle = true
				dead_jungle = true
				frosted_jungle = true
				golden_jungle = true
				golden_apple_jungle = true
				golden_cherry_jungle = true
				magenta_flower_jungle = true
				orange_jungle = true
				red_jungle = true
				white_flower_jungle = true
				apple_oak = true
				cherry_oak = true
				dead_oak = true
				frosted_oak = true
				golden_oak = true
				golden_apple_oak = true
				golden_cherry_oak = true
				magenta_flower_oak = true
				orange_oak = true
				red_oak = true
				white_flower_oak = true
				apple_spruce = true
				cherry_spruce = true
				dead_spruce = true
				frosted_spruce = true
				golden_spruce = true
				golden_apple_spruce = true
				golden_cherry_spruce = true
				magenta_flower_spruce = true
				orange_spruce = true
				red_spruce = true
				white_flower_spruce = true

			[general.types.leaves_type.witherstormmod]
				tainted = true

			[general.types.leaves_type.vinery]
				grapevine = true
				apple = true
				dark_cherry = true

			[general.types.leaves_type.beachparty]
				palm = true

			[general.types.leaves_type.gtceu]
				rubber = true

			[general.types.leaves_type.autumnity]
				maple = true
				yellow_maple = true
				orange_maple = true
				red_maple = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.ad_astra]
				glacian = true

		[general.types.wood_type]

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.beachparty]
				palm = true

			[general.types.wood_type.gtceu]
				rubber = true

			[general.types.wood_type.autumnity]
				maple = true

			[general.types.wood_type.betterarcheology]
				rotten = true

			[general.types.wood_type.ad_astra]
				aeronos = true
				strophar = true
				glacian = true

			[general.types.wood_type.cataclysm]
				chorus = true

	#Disables specific entries
	[general.entries]

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

		[general.entries.wood_type]

			[general.entries.wood_type.chipped]
				fine_planks = true
				checkered_trapdoor = true
				overgrown_trapdoor = true
				overgrown_door = true
				windowed_door = true
				tiled_door = true
				classic_trapdoor = true
				circle_glass = true
				pegged_planks = true
				torch = true
				secret_door = true
				smooth_planks = true
				screen_door = true
				bared_glass = true
				ornate_bared_glass = true
				hewn_planks = true
				crossed_planks = true
				beach_door = true
				fine_vertical_planks = true
				cross_laced_planks = true
				diamond_bordered_glass = true
				railed_planks = true
				planks_mosaic = true
				distorted_trapdoor = true
				iron_barred_trapdoor = true
				circle_glass_pane = true
				versailles_planks = true
				whirlwind_planks = true
				large_diamond_glass_pane = true
				framed_planks = true
				square_glass = true
				vined_trapdoor = true
				barrel = true
				woven_glass = true
				detailed_planks = true
				woven_trapdoor = true
				cobweb_trapdoor = true
				gated_door = true
				supported_door = true
				barred_trapdoor = true
				line_bared_glass_pane = true
				horizontal_lined_glass_pane = true
				airy_trapdoor = true
				line_bared_glass = true
				slanted_planks = true
				barred_door = true
				suspicious_trapdoor = true
				herringbone_planks = true
				pressed_door = true
				planks_panel = true
				vertically_railed_planks = true
				bared_glass_pane = true
				diamond_bordered_glass_pane = true
				solid_trapdoor = true
				tiled_planks = true
				boarded_door = true
				dual_paneled_door = true
				square_glass_pane = true
				meshed_trapdoor = true
				thin_planks = true
				fancy_trapdoor = true
				paper_door = true
				warted_trapdoor = true
				basket_woven_planks = true
				enclosed_planks = true
				double_herringbone_planks = true
				crated_planks = true
				horizontal_lined_glass = true
				natural_planks = true
				classic_windowed_trapdoor = true
				brick_bond_planks = true
				wickered_planks = true
				bordered_glass_pane = true
				sliding_door = true
				heavy_trapdoor = true
				bordered_glass = true
				laced_planks = true
				boxed_planks = true
				reinforced_crate = true
				large_diamond_glass = true
				snowflake_glass_pane = true
				bricky_planks = true
				slotted_trapdoor = true
				shack_door = true
				polished_planks = true
				ornate_bared_glass_pane = true
				diagonal_planks = true
				wall_torch = true
				crate = true
				nailed_planks = true
				cornered_planks = true
				shifted_planks = true
				vertical_planks = true
				glass_door = true
				fortified_door = true
				paneled_door = true
				leafy_trapdoor = true
				snowflake_glass = true
				heavy_door = true
				pointless_trapdoor = true
				stacked_planks = true
				planks_shavings = true
				twisted_trapdoor = true
				diamond_planks = true
				woven_glass_pane = true
				windowed_trapdoor = true
				tile_windowed_door = true
				golden_barred_trapdoor = true

			[general.entries.wood_type.quark]
				vertical_planks = true
				ladder = true
				post = true
				trapped_chest = true
				chest = true
				hollow_log = true
				bookshelf = true
				stripped_post = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.storagedrawers]
				full_drawers_2 = true
				full_drawers_4 = true
				full_drawers_1 = true
				half_drawers_1 = true
				half_drawers_4 = true
				half_drawers_2 = true
				trim = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

